//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int Id { get; set; }
        public Nullable<int> Fk_Producto { get; set; }
        public Nullable<int> Fk_Usuario { get; set; }
        public Nullable<System.DateTime> Fecha_Compra { get; set; }
        public Nullable<System.DateTime> Fecha_Entrega_Maxima { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<System.DateTime> Direccion_Entrega { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
